### ISSUE TITLE
Завдання 5.6.1 "Мейн сторінк" : Виправлення помилок які були приставлені в коментарі.

### ISSUE THREAD

**Issue by AndriyUKRAINE** [V1rs999/Vistra#31]

**Comment by V1rs999** [comment]
DOM Elements
    Search Icon
      1) should toggle the search_input class when clicked
    Sub Menu
      2) should toggle the open-menu class when clicked
    Header Slider
      3) should change the header elements after each slide
    Movie Box
      4) should scroll when left or right arrow is clicked
    Year Button
      5) should show/hide year options when clicked
    A-Z Button
      6) should show/hide A-Z options when clicked


  0 passing (156ms)
  6 failing

  1) DOM Elements
       Search Icon
         should toggle the search_input class when clicked:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

false !== true

      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\script.test.js:61:14)
      at process.processImmediate (node:internal/timers:471:21)

  2) DOM Elements
       Sub Menu
         should toggle the open-menu class when clicked:
     ReferenceError: toggleMenu is not defined
      at Context.<anonymous> (test\script.test.js:71:7)
      at process.processImmediate (node:internal/timers:471:21)

  3) DOM Elements
       Header Slider
         should change the header elements after each slide:
     ReferenceError: slider_load is not defined
      at Context.<anonymous> (test\script.test.js:80:7)
      at process.processImmediate (node:internal/timers:471:21)

  4) DOM Elements
       Movie Box
         should scroll when left or right arrow is clicked:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

0 !== -150

      + expected - actual

      -0
      +-150

      at Context.<anonymous> (test\script.test.js:111:14)
      at process.processImmediate (node:internal/timers:471:21)

  5) DOM Elements
       Year Button
         should show/hide year options when clicked:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

false !== true

      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\script.test.js:123:14)
      at process.processImmediate (node:internal/timers:471:21)

  6) DOM Elements
       A-Z Button
         should show/hide A-Z options when clicked:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

false !== true

      + expected - actual

      -false
      +true

      at Context.<anonymous> (test\script.test.js:134:14)
      at process.processImmediate (node:internal/timers:471:21)
